AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'test/**/*'
    - 'deploy/*'
    - '**/Gemfile'
    - 'config/puma.rb'
    - 'config/spring.rb'
    - 'config/environments/**'
Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'app/**/*'
    - 'config/**/*'

Metrics/LineLength:
  Max: 120

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%w': '[]'
    '%i': '[]'

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Metrics/MethodLength:
  Max: 15
